---
version: "3.7"

services:

  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: payments-db
      POSTGRES_USER: payments-user
      POSTGRES_PASSWORD: payments-password

  payments-api:
    build: .
    ports:
    - 8080:8080
    links:
      - db
    environment:
     JMX_PORT: 1099
     DATABASE_URL: jdbc:postgresql://db:5432
     DATABASE_USER: payments-user
     DATABASE_PASSWORD: payments-password
