management:
  endpoints.web:
    base-path: /
    path-mapping.health: healthcheck
  endpoint.health.show-details: always
  metrics.export.graphite:
    enabled: ${METRICS_EXPORT_ENABLED:false}
    port: 2003
    protocol: Plaintext
    step: PT10S

logging.path: log

spring:
  application.name: payments-api
  data.rest.base-path: /api/v1
  zipkin.baseUrl: ${ZIPKIN_URL:locallhost}
  sleuth.sampler.probability: ${ZIPKIN_SAMPLE_RATE:0.1f}

  datasource:
    url: ${DATABASE_URL}/payments-db
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa.hibernate.ddl-auto: validate
  jpa.show-sql: true

